const data = {
  id: 65,
  username: '吕道锋',
  roleNameDisplays: ['平台管理员非超管'],
  roleNames: ['ptglydrBK'],
  phone: '15757135989',
  userType: 1,
  userTypeShow: '平台用户',
  menus: [
    {
      id: 1,
      title: '企业信息',
      path: '/#',
      children: [
        {
          id: 5,
          title: '员工管理',
          path: '/#',
          children: [
            { id: 6, title: '角色列表', path: '/enterprise/role', children: null },
            { id: 7, title: '用户列表', path: '/enterprise/user', children: null },
          ],
        },
      ],
    },
    {
      id: 2,
      title: '客服管理',
      path: '/#',
      children: [
        {
          id: 8,
          title: '工单管理',
          path: '/enterprise/user',
          children: [{ id: 9, title: '工单列表', path: '/customer/work-list', children: null }],
        },
      ],
    },
    {
      id: 3,
      title: '业务管理',
      path: '/#',
      children: [
        {
          id: 10,
          title: '配置中心',
          path: '/#',
          children: [{ id: 11, title: '规则配置', path: '/business/rules', children: null }],
        },
        {
          id: 17,
          title: '运力中心',
          path: '/#',
          children: [
            { id: 21, title: '审核入驻', path: '/business/audit-enter', children: null },
            { id: 22, title: '资料审核', path: '/business/data-audit', children: null },
            { id: 23, title: '健康申报', path: '/business/health', children: null },
            { id: 18, title: '车辆列表', path: '/business/cars', children: null },
            { id: 19, title: '车型列表', path: '/business/cars-type', children: null },
            { id: 20, title: '司机列表', path: '/business/drivers', children: null },
          ],
        },
        {
          id: 24,
          title: '风控中心',
          path: '/#',
          children: [
            { id: 25, title: '司机处罚记录', path: '/business/driver-punish', children: null },
            { id: 26, title: '订单冻结记录', path: '/business/order-freeze', children: null },
            { id: 100, title: '司机申诉列表', path: '/business/appeal-record', children: null },
          ],
        },
        {
          id: 12,
          title: '财务中心',
          path: '/#',
          children: [
            { id: 13, title: '司机账户', path: '/business/driver-account', children: null },
            { id: 32, title: '提现记录', path: '/business/withdraw-record', children: null },
            { id: 33, title: '发票管理', path: '/business/invoice', children: null },
          ],
        },
        {
          id: 14,
          title: '运营中心',
          path: '/#',
          children: [
            { id: 15, title: '奖励活动', path: '/business/reward', children: null },
            { id: 16, title: '拉新活动', path: '/business/pull-new', children: null },
          ],
        },
        {
          id: 34,
          title: '订单中心',
          path: '/#',
          children: [{ id: 35, title: '订单列表', path: '/business/order-list', children: null }],
        },
      ],
    },
    {
      id: 4,
      title: '平台管理',
      path: '/#',
      children: [
        {
          id: 27,
          title: '商户管理',
          path: '/#',
          children: [
            { id: 28, title: '运营主体列表', path: '/platform/operation', children: null },
          ],
        },
        {
          id: 29,
          title: '员工管理',
          path: '/#',
          children: [
            { id: 30, title: '平台角色列表', path: '/platform/role', children: null },
            { id: 31, title: '平台用户列表', path: '/platform/user', children: null },
          ],
        },
      ],
    },
  ],
  permissions: [
    {
      permissionId: 1,
      permissionName: 'enterpriseRoleList',
      displayName: '商户角色列表',
      url: '/owlc/v1/role/search_operation_entity_role',
    },
    {
      permissionId: 9,
      permissionName: 'enterpriseUserList',
      displayName: '商户用户列表',
      url: '/owlc/v1/merchant-user/page',
    },
    {
      permissionId: 23,
      permissionName: 'workExport',
      displayName: '工单导出',
      url: '/owlc/v1/work_order/export',
    },
    {
      permissionId: 29,
      permissionName: 'workDetail',
      displayName: '工单详情',
      url: '/owlc/v1/work_order/detail/{workNo}',
    },
    {
      permissionId: 45,
      permissionName: 'workRelation',
      displayName: '工单详情-关联工单展示',
      url: '/owlc/v1/work_order/relationWorkOrder',
    },
    {
      permissionId: 47,
      permissionName: 'workRiskHandle',
      displayName: '工单页-风控处置展示',
      url: '/owlc/v1/work_order/riskHandler/{workNo}',
    },
    {
      permissionId: 51,
      permissionName: 'workSearchOrder',
      displayName: '根据条件查询乘客订单列表',
      url: '/owlc/orderList/phone',
    },
    {
      permissionId: 55,
      permissionName: 'workOrderRecord',
      displayName: '获取订单操作记录',
      url: '/owlc/v1/work_order//handleRecord/{orderNo}',
    },
    {
      permissionId: 57,
      permissionName: 'rulesDrawList',
      displayName: '提现规则查询',
      url: '/owlc/v1/strategy/draw_money/page',
    },
    {
      permissionId: 59,
      permissionName: 'registerRuleDetail',
      displayName: '入驻规则查询',
      url: '/owlc/v1/register_rule/detail',
    },
    {
      permissionId: 61,
      permissionName: 'rulesCancelList',
      displayName: '取消规则查询',
      url: '/owlc/v1/driver/cancel_rules/page',
    },
    {
      permissionId: 63,
      permissionName: 'rulesPayList',
      displayName: '垫付规则查询',
      url: '/owlc/v1/platform_pay/page',
    },
    {
      permissionId: 65,
      permissionName: 'rulesDeductList',
      displayName: '抽成规则查询',
      url: '/owlc/v1/deductRule/page',
    },
    {
      permissionId: 67,
      permissionName: 'rulesReportList',
      displayName: '申报规则查询',
      url: '/owlc/v1/health_report_rule/page',
    },
    {
      permissionId: 403,
      permissionName: 'drawMoneyDetails',
      displayName: '提现规则客服详情',
      url: '/config-backstage/v1/drawMoney/details',
    },
    {
      permissionId: 405,
      permissionName: 'cancelRuleDetails',
      displayName: '取消规则客服详情',
      url: '/config-backstage/v1/cancelRules/details ',
    },
    {
      permissionId: 407,
      permissionName: 'healthReportRulePageDetail',
      displayName: '申报规则客服详情',
      url: '/config-backstage/v1/healthRule/pageDetail',
    },
    {
      permissionId: 409,
      permissionName: 'deductRulePageDetail',
      displayName: '抽成规则客服详情',
      url: '/config-backstage/v1/deductRule/pageDetail',
    },
    {
      permissionId: 69,
      permissionName: 'auditEnterList',
      displayName: '审核入驻列表查询',
      url: '/owlc/v1/register/list',
    },
    {
      permissionId: 71,
      permissionName: 'auditEnterDetail',
      displayName: '审核入住详情查询',
      url: '/owlc/v1/register/audit_detail',
    },
    {
      permissionId: 73,
      permissionName: 'auditDataList',
      displayName: '资料审核列表查询',
      url: '/owlc/v1/driver_info_complete/page',
    },
    {
      permissionId: 75,
      permissionName: 'auditDataDetail',
      displayName: '资料审核详情查询',
      url: '/owlc/v1/driver_info_complete/detail',
    },
    {
      permissionId: 77,
      permissionName: 'driverHealthList',
      displayName: '健康申报列表查询',
      url: '/owlc/v1/boss/driver_health/page',
    },
    {
      permissionId: 79,
      permissionName: 'driverHealthDetail',
      displayName: '健康申报详情查询',
      url: '/owlc/v1/driver_health/detail/',
    },
    {
      permissionId: 121,
      permissionName: 'carsList',
      displayName: '车辆列表查询',
      url: '/owlc/v1/cars',
    },
    {
      permissionId: 123,
      permissionName: 'carsBase',
      displayName: '基础信息查询',
      url: '/owlc/v1/car/detail_basic/{carId}',
    },
    {
      permissionId: 125,
      permissionName: 'carsAttach',
      displayName: '附加信息查询',
      url: '/owlc/v1/car/detail_attach/{carId}',
    },
    {
      permissionId: 127,
      permissionName: 'carsTypeList',
      displayName: '车型列表查询',
      url: '/owlc/v1/car_types',
    },
    {
      permissionId: 133,
      permissionName: 'driverList',
      displayName: '司机列表查询',
      url: '/owlc/v1/drivers',
    },
    {
      permissionId: 135,
      permissionName: 'driverBase',
      displayName: '司机详情查询-基本详情',
      url: '/owlc/v1/driver/detail_basic/',
    },
    {
      permissionId: 137,
      permissionName: 'driverAttach',
      displayName: '司机详情查询-附加详情',
      url: '/owlc/v1/driver/detail_attach/',
    },
    {
      permissionId: 139,
      permissionName: 'driverReport',
      displayName: '司机详情查询-出收车记录',
      url: '/owlc/v1/driver/carReportInfos',
    },
    {
      permissionId: 141,
      permissionName: 'driverCompany',
      displayName: '司机详情查询-运力公司变更记录',
      url: '/owlc/v1/driver/company_change_log/',
    },
    {
      permissionId: 81,
      permissionName: 'driverPunishList',
      displayName: '司机处罚记录列表查询',
      url: '/owlc/v1/complaint/pageQuery',
    },
    {
      permissionId: 83,
      permissionName: 'orderFreezeList',
      displayName: '订单冻结记录列表查询',
      url: '/owlc/v1/lock/order/search',
    },
    {
      permissionId: 103,
      permissionName: 'driverAccountList',
      displayName: '司机账户列表',
      url: '/owlc/v1/boss/account/driver/query',
    },
    {
      permissionId: 105,
      permissionName: 'driverTransactionList',
      displayName: '司机流水列表',
      url: '/owlc/v1/boss/account/transactions/query/{driverNo}',
    },
    {
      permissionId: 107,
      permissionName: 'driverWithdrawList',
      displayName: '司机提现列表',
      url: '/owlc/v1/boss/account/withdraw/query',
    },
    {
      permissionId: 159,
      permissionName: 'invoiceQueryPage',
      displayName: '发票管理列表',
      url: '/owlc/v1/boss/invoice/queryPage',
    },
    {
      permissionId: 161,
      permissionName: 'invoiceDetail',
      displayName: '发票管理详情',
      url: '/owlc/v1/boss/invoice/{invoiceId}',
    },
    {
      permissionId: 163,
      permissionName: 'invoicePage',
      displayName: '发票订单信息',
      url: '/owlc/v1/boss/invoice/page',
    },
    {
      permissionId: 109,
      permissionName: 'rewardList',
      displayName: '奖励活动查询',
      url: '/owlc/v1/activity_reward/page',
    },
    {
      permissionId: 111,
      permissionName: 'rewardDetail',
      displayName: '活动信息查询',
      url: '/owlc/v1/activity_reward/detailReward',
    },
    {
      permissionId: 113,
      permissionName: 'rewardStat',
      displayName: '奖励明细查询',
      url: '/owlc/v1/activity_reward/rewardStatisticDetail',
    },
    {
      permissionId: 115,
      permissionName: 'inviteList',
      displayName: '拉新活动列表',
      url: '/owlc/v1/boss/invite/page',
    },
    {
      permissionId: 117,
      permissionName: 'inviteDetail',
      displayName: '拉新活动详情',
      url: '/owlc/v1/boss/invite/{id}',
    },
    {
      permissionId: 119,
      permissionName: 'inviteRewardList',
      displayName: '活动奖励列表',
      url: '/owlc/v1/boss/invite/reward/{activityNo}',
    },
    {
      permissionId: 165,
      permissionName: 'orderList',
      displayName: '订单列表',
      url: '/owlc/v1/boss/es/orders',
    },
    {
      permissionId: 167,
      permissionName: 'orderDetail',
      displayName: '订单详情',
      url: '/owlc/v1/boss/es/orders/{orderNo}',
    },
    {
      permissionId: 85,
      permissionName: 'operationList',
      displayName: '运营主体查询',
      url: '/owlc/v1/operation-entity/page',
    },
    {
      permissionId: 87,
      permissionName: 'operationCreate',
      displayName: '运营主体新增',
      url: '/owlc/v1/operation-entity/create',
    },
    {
      permissionId: 89,
      permissionName: 'operationEdit',
      displayName: '运营主体编辑',
      url: '/owlc/v1/operation-entity/update',
    },
    {
      permissionId: 91,
      permissionName: 'operationDetail',
      displayName: '运营主体详情',
      url: '/owlc/v1/operation-entity/detail/{id}',
    },
    {
      permissionId: 93,
      permissionName: 'platTupleList',
      displayName: '数据组查询',
      url: '/owlc/v1/data-tuple/page',
    },
    {
      permissionId: 95,
      permissionName: 'platTupleCreate',
      displayName: '数据组提交',
      url: '/owlc/owlc/v1/data-tuple/create',
    },
    {
      permissionId: 97,
      permissionName: 'platTupleDelete',
      displayName: '数据组删除',
      url: '/owlc/v1/data-tuple/delete',
    },
    {
      permissionId: 99,
      permissionName: 'platTuplePreCreate',
      displayName: '数据组添加',
      url: '/owlc/v1/data-tuple/pre-create',
    },
    {
      permissionId: 143,
      permissionName: 'platRoleList',
      displayName: '平台角色列表（查询）',
      url: '/owlc/v1/role/search_plat_role',
    },
    {
      permissionId: 145,
      permissionName: 'platRoleCreate',
      displayName: '平台角色新增',
      url: '/owlc/v1/role/create_plat_role',
    },
    {
      permissionId: 147,
      permissionName: 'platRoleEdit',
      displayName: '平台角色修改',
      url: '/owlc/v1/role/update_plat_role',
    },
    {
      permissionId: 149,
      permissionName: 'platRoleStatus',
      displayName: '平台角色启用/禁用',
      url: '/owlc/v1/role/update_plat_role_status/{id}/{status}',
    },
    {
      permissionId: 151,
      permissionName: 'platUserList',
      displayName: '平台用户查询',
      url: '/owlc/v1/platform-user/page',
    },
    {
      permissionId: 153,
      permissionName: 'platUserCreate',
      displayName: '平台用户新增',
      url: '/owlc/v1/platform-user/page',
    },
    {
      permissionId: 155,
      permissionName: 'platUserEdit',
      displayName: '平台用户修改',
      url: '/owlc/v1/platform-user/update-user',
    },
    {
      permissionId: 157,
      permissionName: 'platUserStatus',
      displayName: '平台用户启用/禁用',
      url: '/owlc/v1/platform-user/update-user',
    },
    {
      permissionId: 19,
      permissionName: 'workList',
      displayName: '分页查询',
      url: '/owlc/v1/work_order/page',
    },
    {
      permissionId: 419,
      permissionName: 'appealHandlePageQuery',
      displayName: '搜索列表 ',
      url: '/risk-backstage/v1/appeal_handle/page_query',
    },
    {
      permissionId: 421,
      permissionName: 'appealHandleDetail',
      displayName: '详情',
      url: '/risk-backstage/v1/appeal_handle/detail',
    },
  ],
  permissionNames: null,
  associateAll: null,
  operationEntities: [
    { id: 1, operationEntityName: '蔡振亚运营主体' },
    { id: 3, operationEntityName: '程勇桥运营主体' },
    { id: 5, operationEntityName: '刘哲-运营主体' },
    { id: 7, operationEntityName: '郭亚丽-运营主体' },
    { id: 9, operationEntityName: '吕小武运营主体' },
    { id: 11, operationEntityName: '程勇桥运营主体2' },
    { id: 13, operationEntityName: '小新运营主体' },
    { id: 15, operationEntityName: '运泽运营主体' },
    { id: 17, operationEntityName: '小新运营主体1' },
    { id: 19, operationEntityName: '运泽AA运营主体' },
    { id: 21, operationEntityName: '运泽多彩运营主体' },
    { id: 23, operationEntityName: '运泽飞豹运营主体' },
    { id: 25, operationEntityName: '运泽飞滴运营主体' },
    { id: 27, operationEntityName: '运泽网路运营主体' },
    { id: 29, operationEntityName: '运泽呼我运营主体' },
    { id: 31, operationEntityName: '运泽哎哟喂蓝道运营主体' },
    { id: 43, operationEntityName: '云' },
    { id: 45, operationEntityName: '测试新增' },
    { id: 47, operationEntityName: '测试新增刷新' },
    { id: 49, operationEntityName: '测试新增刷新1' },
    { id: 51, operationEntityName: '小新运营主体2' },
    { id: 53, operationEntityName: '张波运营主体' },
    { id: 55, operationEntityName: '小小运营主体' },
    { id: 57, operationEntityName: '小小运营主体二' },
    { id: 59, operationEntityName: '撒的非让' },
    { id: 61, operationEntityName: '大大运营主体' },
    { id: 63, operationEntityName: '运营主体四' },
    { id: 65, operationEntityName: '徐飘飘运营主体' },
    { id: 67, operationEntityName: '糖果运营主体' },
  ],
  customerNumbers: null,
}
